package com.crm.commons;

/**
 * @author walker tu
 * @date 2017/10/5
 * @description 资源常量的枚举
 */
public enum ResourceConstantEnum {
    SYS_MANAGE,
    USER_MANAGE,
    SYS_USER_VIEW,
    SYS_USER_UPDATE,
    SYS_USER_DELETE,
    SYS_USER_SAVE,
    SYS_USER_ALLOC_ROLE,
    ROLE_MANAGE,
    SYS_ROLE_VIEW,
    SYS_ROLE_UPDATE,
    SYS_ROLE_DELETE,
    SYS_ROLE_SAVE,
    SYS_ROLE_ALLOC_RESOURCE,
    AUTHORIZATION_MANAGE,
    COMPANY_MANAGE,
    SYS_COMPANY_SAVE,
    SYS_COMPANY_UPDATE,
    SYS_COMPANY_VIEW,
    SYS_COMPANY_DELETE,
    DEPT_MANAGE,
    SYS_DEPT_SAVE,
    SYS_DEPT_DELETE,
    SYS_DEPT_VIEW,
    SYS_DEPT_UPDATE,
    MENU_MANAGE,
    SYS_MENU_SAVE,
    SYS_MENU_DELETE,
    SYS_MENU_UPDATE,
    SYS_MENU_VIEW,
    SYS_MENU_ALLOC_RESOURCE,
    SERVICE_MANAGE,
    SYS_SERVICE_INTO,
    COMPLAINT_ACCEPT,
    SYS_COMPLAINT_ACCTPT_SAVE,
    SYS_COMPLAINT_ACCTPT_VIEW,
    SYS_COMPLAINT_ACCTPT_UPDATE,
    COMPLAINT_DISPOSE,
    SYS_DISPOSE_UPDATE,
    SYS_DISPOSE_VIEW,
    LOG_RECORD,
    SYS_LOG_VIEW
}
